version: '3.8'

services:
  email-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-api
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SmtpUsername=nanyim.alain@gmail.com
      - EmailSettings__SmtpPassword=ekcc pfre ybmb iuol
      - EmailSettings__FromEmail=noreply@pioloop.com
      - EmailSettings__FromName=Pioloop
    networks:
      - pioloop-network

networks:
  pioloop-network:
    external: true
