version: '3.8'

services:
  email-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SmtpUsername=nanyim.alain@gmail.com
      - EmailSettings__SmtpPassword=ekcc pfre ybmb iuol
      - EmailSettings__FromEmail=noreply@pioloop.com
      - EmailSettings__FromName=Pioloop
      - Auth__EmailVerificationExpiration=10
    networks:
      - email-network

networks:
  email-network:
    driver: bridge
