version: '3.8'

services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=auth-db;Database=pioloop_auth;Username=pioloop12345;Password=piolOOP_&!?12345;Port=5432
      # JWT Settings
      - JwtSettings__SecretKey=Pioloop2025SecretKey32CharsLong!@#
      - JwtSettings__Issuer=Pioloop
      - JwtSettings__Audience=PioloopUsers
      - JwtSettings__ExpirationHours=24
      # Email Settings
      - EmailApi__BaseUrl=http://localhost:5002
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SmtpUsername=nanyim.alain@gmail.com
      - EmailSettings__SmtpPassword=ekcc pfre ybmb iuol
      - EmailSettings__FromEmail=noreply@pioloop.com
      - EmailSettings__FromName=Pioloop

      # Stripe Settings
      - StripeSettings__SecretKey=your-stripe-secret-key
      - StripeSettings__PublishableKey=your-stripe-publishable-key
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - auth-network
    restart: unless-stopped

  auth-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=pioloop_auth
      - POSTGRES_USER=pioloop12345
      - POSTGRES_PASSWORD=piolOOP_&!?12345
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pioloop12345 -d pioloop_auth"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  auth-db-data:

networks:
  auth-network:
    driver: bridge
